language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install freezegun
- pip install nose
- python setup.py install
script: nosetests
deploy:
  provider: pypi
  user: $USERNAME
  password: $PASSWORD
  skip_existing: true
  on:
    tags: true