language: python
python:
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install freezegun
- pip install nose
- python setup.py install
script: nosetests
deploy:
  user: $USERNAME
  password: $PASSWORD
  on:
    tags: true